import os
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from flask import Flask, request, jsonify, render_template
from flask_cors import CORS
from openai import OpenAI
import google.genai as genai
import requests

app = Flask(__name__)
CORS(app)

# ============================================
# 1. Model & Endpoint Configuration (2026 Active)
# ============================================
PROVIDER_CONFIG = {
    "deepseek":   {"base_url": "https://api.deepseek.com",           "model": "deepseek-chat"},
    "github":     {"base_url": "https://models.github.ai/inference", "model": "gpt-4o-mini"},
    "groq":       {"base_url": "https://api.groq.com/openai/v1",     "model": "llama-3.3-70b-versatile"},
    "openrouter": {"base_url": "https://openrouter.ai/api/v1",       "model": "deepseek/deepseek-r1:free"},
}
# ✅ Fixed back to the correct 2026 model
GEMINI_DEFAULT_MODEL = "gemini-2.5-flash"

# ============================================
# 2. Helper Functions to Create Clients
# ============================================
def get_openai_client(provider, api_key):
    config = PROVIDER_CONFIG.get(provider)
    if config:
        return OpenAI(api_key=api_key, base_url=config["base_url"])
    return None

def get_gemini_client(api_key):
    return genai.Client(api_key=api_key)

# ============================================
# 3. Universal AI Call Function (Handles Custom Models)
# ============================================
def call_ai(prompt, provider, api_key, custom_model=None):
    if not api_key:
        return f"Error: No API key provided for {provider}."
    try:
        if provider == "gemini":
            client = get_gemini_client(api_key)
            model_name = custom_model or GEMINI_DEFAULT_MODEL
            resp = client.models.generate_content(model=model_name, contents=prompt)
            return resp.text.strip()
        else:
            client = get_openai_client(provider, api_key)
            config = PROVIDER_CONFIG.get(provider)
            if not client or not config:
                return f"Error: {provider} configuration issue."
            model_name = custom_model or config["model"]
            resp = client.chat.completions.create(
                model=model_name,
                messages=[{"role": "user", "content": prompt}],
                timeout=30
            )
            return resp.choices[0].message.content
    except Exception as e:
        return f"Error ({provider}): {str(e)}"

# ============================================
# 4. Parallel Debate Engine (Supports Multi-Keys)
# ============================================
def debate_parallel(prompt, api_keys):
    tasks = []
    for provider, keys in api_keys.items():
        if isinstance(keys, list):
            for idx, key in enumerate(keys):
                tasks.append((provider, key, f"{provider}-Agent-{idx+1}"))

    if not tasks:
        return {"System": "Error: No active API keys found."}
    
    with ThreadPoolExecutor(max_workers=min(len(tasks), 10)) as executor:
        future_to_task = {
            executor.submit(call_ai, prompt, provider, key): agent_label 
            for provider, key, agent_label in tasks
        }
        
        results = {}
        for future in as_completed(future_to_task):
            agent_label = future_to_task[future]
            try:
                results[agent_label] = future.result()
            except Exception as e:
                results[agent_label] = f"Error: {str(e)}"
        return results

# ============================================
# 5. Justice AI (Recommendation Mode - Debate OFF)
# ============================================
def justice_ai_recommendation(debate_results, original_prompt, api_keys, justice_provider, justice_key):
    if not justice_key:
        for p in ["gemini", "deepseek", "groq", "github", "openrouter"]:
            if p in api_keys and isinstance(api_keys[p], list) and len(api_keys[p]) > 0:
                justice_provider = p
                justice_key = api_keys[p][0]
                break
        if not justice_key:
            return "Justice AI Error: No valid API key provided or available in pool."

    formatted_responses = "\n\n".join([f"--- [{agent}] ---\n{resp[:1000]}" for agent, resp in debate_results.items()])
    
    recommendation_prompt = f"""You are Justice AI, an impartial and expert AI evaluator.
Below are multiple answers generated by different AI models for the same prompt.

User Original Prompt:
{original_prompt}

AI Model Responses:
{formatted_responses}

Task:
1. Compare and evaluate all responses for technical accuracy, clarity, and completeness.
2. Clearly state which AI Agent provided the BEST response and why.
3. Present the winning response or a refined synthesis as your final recommendation."""

    return call_ai(recommendation_prompt, justice_provider, justice_key)

# ============================================
# 6. Consensus Debate Engine (Debate ON)
# ============================================
def consensus_debate(prompt, api_keys):
    # Round 1: Initial Answers
    round1_results = debate_parallel(prompt, api_keys)
    formatted_r1 = "\n\n".join([f"[{agent}]: {resp}" for agent, resp in round1_results.items()])
    
    # Round 2: Cross-Critique
    critique_prompt = f"User Prompt: {prompt}\n\nReview these initial answers from other agents and provide constructive critique:\n\n{formatted_r1}"
    critique_results = debate_parallel(critique_prompt, api_keys)
    formatted_critiques = "\n\n".join([f"[{agent} Critique]: {resp}" for agent, resp in critique_results.items()])
    
    # Round 3: Refinement & Final Consensus
    consensus_prompt = f"User Prompt: {prompt}\n\nCritiques received:\n{formatted_critiques}\n\nPlease synthesize the absolute best, error-free consensus answer that incorporates all valid corrections."
    
    consensus_results = debate_parallel(consensus_prompt, api_keys)
    
    for agent, text in consensus_results.items():
        if not text.startswith("Error:"):
            return f"🤝 **Debate Consensus Answer (Validated by Multi-Agent Pool):**\n\n{text}"
            
    return list(consensus_results.values())[0] if consensus_results else "No consensus reached."

# ============================================
# 7. Main Chat Routes
# ============================================
@app.route('/')
def index():
    return render_template('index.html')

@app.route('/api/chat', methods=['POST'])
def chat():
    data = request.get_json(silent=True) or {}
    mode = data.get('mode', 'General')
    user_message = data.get('message', '')
    debate_on = data.get('debateOn', False)
    api_keys = data.get('apiKeys', {})
    pg_state = data.get('pgState', {})
    
    pg_selector = data.get('pgSelector', {})
    justice_selector = data.get('justiceSelector', {})

    if not user_message.strip():
        return jsonify({"error": "Empty message"}), 400

    if mode == "General":
        base_prompt = "You are a helpful, friendly, and concise AI assistant. Answer clearly and directly."
    else:
        base_prompt = "You are a Senior Software Architect and Lead Developer. Output step-by-step production-grade code, security edge-case analyses, and clear system architecture guidelines."

    anchor_context = ""
    if pg_state.get('locked'):
        core_spec = pg_state.get('coreSpec', 'Defined in prior planning')
        progress = ", ".join(pg_state.get('progress', [])) or "None yet"
        active_focus = pg_state.get('activeFocus', 'Phase 1')
        anchor_context = f"\n[PROJECT GUARDIAN MASTER SPEC]\n- Core Goal: {core_spec}\n- Completed Phases: {progress}\n- Active Focus: {active_focus}\n"

    full_prompt = f"{base_prompt}\n{anchor_context}\nUser Request: {user_message}"

    try:
        if not debate_on:
            debate_results = debate_parallel(full_prompt, api_keys)
            j_provider = justice_selector.get('provider', 'gemini')
            j_key = justice_selector.get('key', '')
            ai_reply = justice_ai_recommendation(debate_results, full_prompt, api_keys, j_provider, j_key)
        else:
            ai_reply = consensus_debate(full_prompt, api_keys)
            
    except Exception as e:
        ai_reply = f"Error processing request: {str(e)}"

    return jsonify({
        "response": ai_reply,
        "mode": mode,
        "debateOn": debate_on
    })

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)
